### PR TITLE
Pedestrian import

### PR DESCRIPTION
**Pull request by IvanKonon0v**
added pedestrian routing to prokect

### CODE REVIEW

**Comment by DCrow** [comment]
Hello! Thank you for your subbmission.

Haven't fully looked over but found these problems.
1. Needs an example page
2. Java indentation should be corrected to match project.
3. Commented code must be removed
4. Newlines at end of files must be added

**Comment by IvanKonon0v** [comment]
Hello! 
Thanks for your answers. I will solve these problems and send it again.

**Comment by IvanKonon0v** [comment]
@DCrow hello 👋  can i ask you, to check my last commit, i`ve solved  issues that you have found

**Comment by IlgamGabdullin** [comment]
@DCrow could you take a look at the pr? waiting for this feature

**Comment by DCrow** [comment]
Implemented in master

**Comment by IlgamGabdullin** [comment]
good news, thanks a lot! waiting for release on pub.dev

**Pull request closed without merging**
